### ISSUE TITLE
期待ing

### ISSUE THREAD

**Issue by tvvocold** [marguerite/marguerite.github.io#1]
:)
PS：请注意百度的蜘蛛现在爬不了 Github Page，因为之前 Github 被 DDos 的事件；不过你可以通过使用 [CDN](https://github.com/ripienaar/free-for-dev#cdn-and-protection) 解决这个问题 （需要在仓库加入 [CNAME](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/) 文件）

**Comment by 1dot75cm** [comment]
期待女神的文章 ^^~
